# -*- coding: utf-8 -*-
"""Assignment_DSML40_Day 34_Alfiah Zalfa Tsabitah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjpYeMeFUan7C809EdyNc68P7nb9OCKc

# Library
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, mean_squared_error

"""# Explorasi Data

## Import Data from Drive
"""

from google.colab import drive
drive.mount('/content/drive')

# import data per bulan
jan = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_january_2019.csv')
feb = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_february_2019.csv')
mar = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_march_2019.csv')
apr = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_april_2019.csv')
may = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_may_2019.csv')
jun = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_june_2019.csv')
jul = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_july_2019.csv')
aug = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_august_2019.csv')
sep = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_september_2019.csv')
oct = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_october_2019.csv')
nov = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_november_2019.csv')
dec = pd.read_csv('/content/drive/MyDrive/DIBIMBING.ID/Assignment 34/ecommerce_time_series_analysis/sales_data_december_2019.csv')

"""## Cek data per bulan"""

# Januari
jan.info()

# Febuari
feb.info()

# Maret
mar.info()

# April
apr.info()

# Mei
may.info()

# Juni
jun.info()

# Juli
jul.info()

# Agustus
aug.info()

# September
sep.info()

# Oktober
oct.info()

# November
nov.info()

# Desember
dec.info()

"""Dikarenakan seluruh data dari januari hingga desember memiliki kolom dan tipe data yang sama, maka data dapat langsung digabungkan menjadi 1

## Gabungkan Data
"""

# Data tahun 2019
df_setahun = pd.concat([jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec], ignore_index=True)
df_setahun

# cek informasi data
df_setahun.info()

"""Data yang telah digabungkan menjadi 1 memiliki 6 kolom dengan 178157 baris dengan tipe data keseluruhan berupa object. Berdasarkan informasi data diatas didapatkan :
1. Data memiliki missing value sebanyak 523 data
2. Tipe data yang tidak sesuai, seperti yang seharusnya integer/datetime tapi semua data masuk ke object

## Buat Copy Data
"""

df = df_setahun.copy()

"""## Cek Header data awal"""

df[df['Order ID'] == 'Order ID']

# hapus header dari penggabungan data diawal
df = df[df['Order ID'] != 'Order ID']

# cek kembali header
df[df['Order ID'] == 'Order ID']

"""## Ubah tipe data"""

# ubah data menjadi numerik
df['Quantity Ordered'] = pd.to_numeric(df['Quantity Ordered'])
df['Price Each'] = pd.to_numeric(df['Price Each'])

# ubah data menjadi datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

# cek type data
df.info()

"""# Pembersihan Data

## Missing Value
"""

# cek missing value
df.isna().sum()

# cek persentase missing value
df.isna().mean()*100

# persentase total missing value
df.isna().mean().sum()*100

# cek bagian mana yang missing
df[df.isnull().any(axis=1)]

# bandingkan missing value sebelum diubah tipe data dan setelah diubah tipe data
# setelah ubah tipe data
df.info()

# sebelum ubah tipe data
df_setahun = df_setahun[df_setahun['Order ID'] != 'Order ID']
df_setahun.info()

"""Kesimpulan :
1. Missing value bukan yang karena perubahan tipe data, namun missing value memang sudah sedari awal ada dan merata diseluruh kolom dengan jumlah dan tempat yang sama setiap baris yang terdapat missing.
2. Persentase keseluruhan missing value yang terdapat pada data tersebut sebanyak 2%, yang artinya jika data di drop tidak akan terlalu berpengaruh besar terhadap data keseluruhan.
"""

# Handle Missing Value
df = df.dropna()

# cek kembali missing value
df.isna().sum()

"""## Duplicates Data"""

# cek duplicates data
df.duplicated().sum()

# cek letak duplicates data
df[df.duplicated(keep=False)]

# handle duplicates data
df = df.drop_duplicates()

# cek kembali duplicates data
df.duplicated().sum()

"""Kesimpulan :
Terdapat duplicate data dan memang setelah diperiksa satu persatu memang data tersebut sama untuk baris yang berbeda, sehingga dilakukan penghapusan data yang duplikat

# Feature Engineering
"""

# Total Revenue
df['Total Revenue'] = df['Quantity Ordered'] * df['Price Each']

# Hour
df['Hour'] = df['Order Date'].dt.hour

# City
df['City'] = df['Purchase Address'].str.split(',').str[1].str.strip()

# cek apakah sudah masuk
df.head()

"""# Outliers"""

# boxplot
plt.boxplot(x=df['Total Revenue'])
plt.show()

# grafik distribusi
plt.hist(df['Total Revenue'])
plt.show()

"""Jika dilihat berdasarkan boxplot dan grafik distribusi pada kolom Total Revenue, maka terdapat outliers. Namun perlu dilakukan pengecekan ulang apakah outlier yang dihasilkan terjadi karena error atau memang ada pemicu lainnya seperti promo sehingga pelanggan membeli dengan jumlah yang berbeda dari kebiasaan rata-rata pelanggan"""

min_value = df['Total Revenue'].min()
max_value = df['Total Revenue'].max()
print("Nilai minimum:", min_value)
print("Nilai maksimum:", max_value)

# IQR
Q1 = df['Total Revenue'].quantile(0.25)
Q3 = df['Total Revenue'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_iqr = df[(df['Total Revenue'] < lower_bound) |
                 (df['Total Revenue'] > upper_bound)]

print("Jumlah outlier (IQR):", len(outlier_iqr))
outlier_iqr.head()

# cek paakah saat tanggal yang sama
outlier_iqr[['Order Date', 'Total Revenue']].sort_values('Total Revenue', ascending=False)

"""jika dicek berdasarkan tanggal maka tidak ada tanggal yang benar2 sama sehingga dapat dikatakan bahwa penyebab outlier pada kolom Total Revenue bukan karena diskon tanggal kembar"""

# cek apakah quantitynya besar
outlier_iqr[['Quantity Ordered', 'Total Revenue']].sort_values('Total Revenue', ascending=False)

"""jika dicek berdasarkan quantity, jumlah yang di order bukan yang terlalu besar, maka penyebab outlier bukan karena jumlah order yang sangat besar"""

# cek berdasarkan harga
outlier_iqr[['Price Each', 'Total Revenue']].sort_values('Total Revenue', ascending=False)

"""Jika dicek berdasarkan harga, maka dapat dilihat penyebab adanya outliers pada kolom Total Revenue adalah karena harga yang memang tinggi, sehingga ketika ada pelanggan yang membeli dengan harga tersebut maka akan menghasilkan outlier karena jarang ada pelanggan yang membeli dengan harga yang tinggi

Kesimpulan :
1. Jika dilihat berdasarkan grafik dan boxplot maka teridentfikasi adanya outlier pada Total Revenue
2. Perlu dilakukan identifikasi lebih lanjut apakah outlier yang dihasilkan karena kesalahan saat penginputan data, atau karena memang ada diskon di tanggal tertentu, atau karena pembelian dengan jumlah yang banyak, atau karena harga yang relatif lebih mahal dibandingkan dengan yang lain
3. Menggunakan metode IQR untuk identifikasi lebih lanjut
4. Outlier muncul dikarenakan harga yang relatif lebih mahal dan bukan karena kesalahan sata penginputan/error sehingga tidak perlu didrop agar saat forecasting nanti data yang dihasilkan menjadi lebih baik

# Informasi data 2019
"""

# filter data 2019
df_2019 = df[df['Order Date'].dt.year == 2019]

# total revenue 2019
total_revenue_2019 = df_2019['Total Revenue'].sum()

# jumlah order 2019
jumlah_order_2019 = df_2019['Quantity Ordered'].sum()

# jumlah barang terjual 2019
jumlah_barang_terjual_2019 = df_2019['Quantity Ordered'].count()

# rata-rata jumlah barang per transaksi
rata2_jumlah_barang_per_transaksi = jumlah_barang_terjual_2019 / jumlah_order_2019

# rata-rata spending per transaksi
rata2_spending_per_transaksi = total_revenue_2019 / jumlah_order_2019

# tampilkan data
print('Total Revenue 2019 :', round(total_revenue_2019, 2))
print('Jumlah Order 2019 :', round(jumlah_order_2019, 2))
print('Jumlah Barang Terjual 2019:', round(jumlah_barang_terjual_2019, 2))
print('Rata-rata Jumlah Barang per Transaksi :', round(rata2_jumlah_barang_per_transaksi, 2))
print('Rata-rata Spending per Transaksi :', round(rata2_spending_per_transaksi, 2))

"""# Analisis Tren dan Pola"""

df

"""## Tren"""

# jadikan datetime sebagain index
df['Order Date'] = pd.to_datetime(df['Order Date'])
df = df.set_index('Order Date')

"""### Harian"""

# ambil tanggal dan agregasi
daily = df.groupby(df.index)['Total Revenue'].sum().reset_index()

# rename kolom
daily.columns = ['Date', 'Total Revenue']

# konversi kolom date
daily['Date'] = pd.to_datetime(daily['Date'])

# tampilkan hasil
daily

plt.figure()
plt.plot(daily['Date'], daily['Total Revenue'])
plt.xlabel("Date")
plt.ylabel("Total Revenue")
plt.title("Daily GMV Trend")
plt.show()

"""### Mingguan"""

# ambil minggu dari index dan agregasi
weekly = df.groupby(pd.Grouper(freq='W'))['Total Revenue'].sum().reset_index()

# rename kolom
weekly.columns = ['Date', 'Total Revenue']

# tampilkan hasil
weekly

plt.figure()
plt.plot(weekly['Date'], weekly['Total Revenue'])
plt.xlabel("Date")
plt.ylabel("Total Revenue")
plt.title("Weekly GMV Trend")
plt.show()

# cek yang total revenuenya 0
weekly[weekly['Total Revenue'] == 0]

"""### Bulanan"""

# ambil bulan dari index dan agregasi
monthly = df.groupby(pd.Grouper(freq='M'))['Total Revenue'].sum().reset_index()

# rename kolom
monthly.columns = ['Date', 'Total Revenue']

# tampilkan hasil
monthly

plt.figure()
plt.plot(monthly['Date'], monthly['Total Revenue'])
plt.xlabel("Date")
plt.ylabel("Total Revenue")
plt.title("Monthly GMV Trend")
plt.show()

"""Kesimpulan :
1. Berdasarkan grafik harian, mingguan, dan bulanan menunjukan pola tren yang fluktuatif.
2. Pada awal tahun terlihat tren kenaikan yang stabil hingga sekitar pada bulan ketiga menuju bulan keempat, kemudian mengalami penurunan dan terjadi lonjakan pada akhir tahun.
3. Berdasarkan grafik terlihat ada penurunan tajam.
4. Dilakukan identifikasi total revenue 0 pada bagian weekly dengan mengecek bagian mana yang memiliki revenue 0, lalu tidak ada yang memiliki total revenue 0

## Top 10 Produk

### Produk yang Paling sering dibeli 1 tahun terakhir
"""

# filter 1 tahun terakhir
last_date = df.index.max()
one_year_ago = last_date - pd.DateOffset(years=1)

df_last_year = df[df.index >= one_year_ago]

top_freq = (
    df_last_year
    .groupby('Product')['Quantity Ordered']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top_freq

plt.figure()
plt.barh(top_freq['Product'], top_freq['Quantity Ordered'], color='pink')
plt.xlabel("Total terjuan")
plt.title("Top 10 Produk Terjual (Last 1 Year)")
plt.gca().invert_yaxis()
plt.show()

"""### Produk dengan revenue terbesar dalam 3 bulan terakhir"""

# filter 3 bulan terakhir
three_month_ago = last_date - pd.DateOffset(months=3)
df_last_3m = df[df.index >= three_month_ago]

top_revenue = (
    df_last_3m
    .groupby('Product')['Total Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top_revenue

plt.figure()
plt.barh(top_revenue['Product'], top_revenue['Total Revenue'], color='pink')
plt.xlabel("Total Revenue")
plt.title("Top 10 Produk Revenue Terbesar (3 Month Ago)")
plt.gca().invert_yaxis()
plt.show()

"""Kesimpulan :
1. Verdasarkan analisis 1 tahun terakhir, produk yang paling sering dibeli adalah produk yang paling sering digunakan dan dibutuhkan, oleh karena itu pelanggan sering melakukan repeat order
2. Berdasarkan analisis 3 bulan terakhir berdasarkan total revenue, produk yang memiliki total revenue terbesar adalah produk yang kemungkinanan memiliki harga satuan yang tinggi atau jumlah pembelian yang banyak
3. Produk yang dapat dibundling adalah produk dengan total revenue tinggi+penjualan banyak, seperti Iphone dengan usb charging cable/lightning charging cable karena kedua barang tersebut sangat berhubungan. Atau bisa juga dengan memberikan diskon khusus untuk pembelian produk dengan harga yang tinggi dan total revenue tinggi, seperti jika membeli macbook pro+iphone akan mendapatkan diskon 30%

## Top 5 kota yang memiliki order terbanyak
"""

top_city_orders = (
    df.groupby('City')['Order ID']
    .nunique()
    .sort_values(ascending=False)
    .head(5)
    .reset_index(name='Total Orders')
)

top_city_orders

plt.figure()
plt.barh(top_city_orders['City'], top_city_orders['Total Orders'], color='pink')
plt.xlabel("Total Order")
plt.title("Top 5 City dengan orderan terbanyak")
plt.gca().invert_yaxis()
plt.show()

"""## Top 5 kota yang memiliki total dan rata-rata spending terbesar

"""

city_spending = (
    df.groupby('City')
    .agg(
        total_spending=('Total Revenue', 'sum'),
        avg_spending=('Total Revenue', 'mean')
    )
    .sort_values(by='total_spending', ascending=False)
)

top5_total_spending = city_spending.head(5)
top5_avg_spending = city_spending.sort_values(by='avg_spending', ascending=False).head(5)

top5_total_spending
top5_avg_spending

plt.barh(top5_total_spending.index, top5_total_spending['total_spending'], color='pink')
plt.xlabel("City")
plt.ylabel("Total Spending")
plt.title("Top 5 Cities by Total Spending")
plt.gca().invert_yaxis()
plt.show()

plt.barh(top5_avg_spending.index, top5_avg_spending['avg_spending'], color='pink')
plt.xlabel("City")
plt.ylabel("Average Spending")
plt.title("Top 5 Cities by Average Spending")
plt.gca().invert_yaxis()
plt.show()

"""## Rush Hour"""

rush_hour = (
    df.groupby('Hour')['Order ID']
    .nunique()
    .reset_index(name='Total Orders')
    .sort_values('Hour')
)

rush_hour

plt.figure()
plt.plot(rush_hour['Hour'], rush_hour['Total Orders'])
plt.xlabel("Hour")
plt.ylabel("Total Orders")
plt.title("Rush Hour")
plt.show()

"""Kesimpulan : Penjualan paling aktif terjadi pada sekitar jam 19 dengan jumlah transaksi sebanyak 10990, karena mencerminkan intensitas aktivitas pelanggan dalam melakukan pembelian.

# Pembuatan Model Forecasting

## Buat index
"""

# Hitung Total Transactions
ts = df.groupby(df.index.date).agg({
    'Total Revenue':'sum',
    'Order ID': pd.Series.nunique
})

ts = ts.rename(columns={'Order ID':'Total Transactions'})

# Ubah index ke datetime
ts.index = pd.to_datetime(ts.index)

# tampilkan hasil
ts.head()

"""## Uji ADF

## Total Revenue
"""

adf_result = adfuller(ts['Total Revenue'])
print(f'ADF Statistic: {adf_result[0]}')
print(f'p-value: {adf_result[1]}')

# Karena data tidak stasioner (p-value > 0.05), maka perlu transformasi data
# Terapkan log transform
A_log = np.log(ts['Total Revenue'])

# Terapkan differencing
A_log_diff = A_log.diff().dropna()

# uji ADF lagi
adf_result = adfuller(A_log_diff)
print(f'ADF Statistic: {adf_result[0]}')
print(f'p-value: {adf_result[1]}')

"""## Total Transaction"""

adf_result = adfuller(ts['Total Transactions'])
print(f'ADF Statistic: {adf_result[0]}')
print(f'p-value: {adf_result[1]}')

# Karena data tidak stasioner (p-value > 0.05), maka perlu transformasi data
# Terapkan log transform
B_log = np.log(ts['Total Transactions'])

# Terapkan differencing
B_log_diff = B_log.diff().dropna()

# uji ADF lagi
adf_result = adfuller(B_log_diff)
print(f'ADF Statistic: {adf_result[0]}')
print(f'p-value: {adf_result[1]}')

"""## Split Data"""

# Total Revenue
train_r = A_log_diff[:'2019-02-28']
test_r = A_log_diff['2019-03-01':]

# Total Transaction
train_t = B_log_diff[:'2019-02-28']
test_t = B_log_diff['2019-03-01':]

# cek nan pad data
print(train_r.isna().sum())
print(test_r.isna().sum())

print(train_t.isna().sum())
print(test_t.isna().sum())

"""## Model

### ARIMA

#### Total Revenue
"""

model_arima = ARIMA(train_r, order=(1,0,1))
result_arima = model_arima.fit()

# Forecast dalam bentuk log
forecast_arima_log_ra = result_arima.forecast(steps=len(test_r))

# Kembalikan hasil forecast ke bentuk asal
forecast_arima_r = np.exp(forecast_arima_log_ra)

"""karena Parameter (1,1,1) artinya: p=1 (Auto REGRESSION), d=1 (differencing), q=1 (MOVING AVERAGE) dan pada uji adf sudah melakuakn differencing, parameter d diubah menjadi 0

#### Total Transaction
"""

model_arima = ARIMA(train_t, order=(1,0,1))
result_arima = model_arima.fit()

# Forecast dalam bentuk log
forecast_arima_log_ta = result_arima.forecast(steps=len(test_t))

# Kembalikan hasil forecast ke bentuk asal
forecast_arima_t = np.exp(forecast_arima_log_ta)

"""### SARIMA

#### Total Revenue
"""

sarima_model = SARIMAX(train_r, order=(1,0,1), seasonal_order=(1,1,1,7))

# Fit model
sarima_result = sarima_model.fit(disp=False)

# Forecast dalam bentuk log
forecast_log_rs = sarima_result.forecast(steps=len(test_r))

# Kembalikan ke bentuk asli
forecast_sarima_r = np.exp(forecast_log_rs)

"""#### Total Transaction"""

sarima_model = SARIMAX(train_t, order=(1,0,1), seasonal_order=(1,1,1,7))

# Fit model
sarima_result = sarima_model.fit(disp=False)

# Forecast dalam bentuk log
forecast_log_ts = sarima_result.forecast(steps=len(test_t))

# Kembalikan ke bentuk asli
forecast_sarima_t = np.exp(forecast_log_ts)

"""## MAPE"""

# mengembalikan split data test ke dalam bentuk asal
actual_r = np.exp(test_r)
actual_t = np.exp(test_t)

mape_arima_r = mean_absolute_percentage_error(actual_r, forecast_arima_r)
mape_arima_t = mean_absolute_percentage_error(actual_t, forecast_arima_t)
mape_sarima_r = mean_absolute_percentage_error(actual_r, forecast_sarima_r)
mape_sarima_t = mean_absolute_percentage_error(actual_t, forecast_sarima_t)

# Tampilkan hasil
print(f'MAPE ARIMA Total Revenue: {mape_arima_r:.2%}')
print(f'MAPE ARIMA Total Transaction: {mape_arima_t:.2%}')
print(f'MAPE SARIMA Total Revenue: {mape_sarima_r:.2%}')
print(f'MAPE SARIMA Total Transaction: {mape_sarima_t:.2%}')

"""dikarenakan data test dan training menggunakan log_diff, maka untuk mengeluarkan nilai MAPE untuk testnya dikembalikan ke data awal agar sesuai dengan hasil forecast model yang sudah dikembalikan ke data awal"""

# Pilih model terbaik
best_model_revenue = "ARIMA" if mape_arima_r < mape_sarima_r else "SARIMA"
best_model_transaction = "ARIMA" if mape_arima_t < mape_sarima_t else "SARIMA"

# Tampilkan model terbaik berdasarkan evaluasi MAPE
print(f"Model beradsarkan Total Revenue terbaik berdasarkan MAPE adalah: {best_model_revenue}")
print(f"Model beradsarkan Total Transaction terbaik berdasarkan MAPE adalah: {best_model_transaction}")

"""## Forecast

### Total Revenue
"""

# gunakan seluruh data
model_best = ARIMA(A_log_diff, order=(1,0,1))

result_best = model_best.fit()

# forecast 30 hari kedepan
forecast_log = result_best.forecast(steps=30)

# kembalikan dalam bentuk asal
forecast_revenue = np.exp(forecast_log)

# buat tanggal
future_dates = pd.date_range(
    start=ts.index[-1] + pd.Timedelta(days=1),
    periods=30
)

# hasil forecast
forecast_df = pd.DataFrame({
    'Date': future_dates,
    'Forecast_Revenue': forecast_revenue
})

forecast_df

plt.figure(figsize=(12,5))

plt.plot(ts.index, ts['Total Revenue'], label='Actual')
plt.plot(forecast_df['Date'], forecast_df['Forecast_Revenue'], label='Forecast 30 Days', color='red')

plt.title('Revenue Forecast for Next 30 Days')
plt.xlabel('Date')
plt.ylabel('Revenue')
plt.legend()
plt.show()

"""### Total Revenue"""

# gunakan seluruh data
model_best = ARIMA(B_log_diff, order=(1,0,1))

result_best = model_best.fit()

# forecast 30 hari kedepan
forecast_log = result_best.forecast(steps=30)

# kembalikan dalam bentuk asal
forecast_revenue = np.exp(forecast_log)

# buat tanggal
future_dates = pd.date_range(
    start=ts.index[-1] + pd.Timedelta(days=1),
    periods=30
)

# hasil forecast
forecast_df = pd.DataFrame({
    'Date': future_dates,
    'Forecast_Revenue': forecast_revenue
})

forecast_df

plt.figure(figsize=(12,5))

plt.plot(ts.index, ts['Total Revenue'], label='Actual')
plt.plot(forecast_df['Date'], forecast_df['Forecast_Revenue'], label='Forecast 30 Days', color='red')

plt.title('Revenue Forecast for Next 30 Days')
plt.xlabel('Date')
plt.ylabel('Revenue')
plt.legend()
plt.show()

"""# Evaluasi dan Interpretasi

Evaluasi Pengerjaan Assignment:
1. Perbandingan antara 2 model, yaitu ARIMA dan SARIMA menghasilkan ARIMA sebagai model terbaik
2. Hasil forecast menjadi sangat rendah, dikarenakan pada split data dan uji adf (karna hasil uji adf lebih dari 0.005) menggunakan alur Data awal → Log → Difference → Model → Forecast_diff, nah seharusnya untuk mengembalikan data dibalik ke alur awal, namun masih ada step yang terlewat, sehingga perlu dipelajari kembali proses pengembalian data ke data awal
3. Perlu mengexplore kembali menggunakan model yang lainnya agar dapat melihat perbandingan yang lebih baik, agar dapat menghasilkan insight yang lebih baik untuk bisnis
4. Untuk insight bisnis, maaf belum bisa diberikan dikarenakan hasil forecast yang belum smepurna

# Reflection Questions

Mengapa penting menganalisis tren waktu (trend & seasonality) sebelum membuat model forecasting, dan bagaimana pengabaian pola musiman bisa memengaruhi keputusan bisnis? Jelaskan dengan contoh bagaimana prediksi yang mengabaikan seasonality dapat menyebabkan salah perencanaan stok atau kampanye pemasaran.

--> Menganalisis tren waktu, termasuk trend dan seasonality, sangat penting sebelum membuat model forecasting karena kedua pola ini dapat mempengaruhi hasil prediksi. Trend menunjukkan arah data dalam jangka panjang, seperti meningkat, menurun, atau stagnan, misalnya perusahaan tidak menambah stok yang cukup saat permintaan produk meningkat, sehingga terjadi kekurangan barang. Sedangkan seasonality adalah pola berulang dalam interval tertentu, seperti mingguan, bulanan, atau tahunan. Mengabaikan pola musiman dapat menyebabkan prediksi jauh dari kenyataan, misalnya toko yang tidak memperhitungkan lonjakan penjualan saat Ramadan sehingga kehabisan stock baju untuk lebaran.

Bagaimana metrik agregasi berbeda (harian, mingguan, bulanan) membantu tim bisnis dalam mengambil keputusan operasional dan strategis? Berikan contoh keputusan yang lebih tepat dibuat dengan data mingguan dibandingkan data harian, atau sebaliknya.

--> Agregasi harian dapat memperlihatkan fluktuasi harian, agregasi mingguan memperlihatkan fluktuasi mingguan, dan agregasi bulanan memperlihatkan fluktuasi bulanan. Hal tersebut dapat membantu tim bisnis untuk menentukan kapan terjadinya peningkatan transaksi. Coontoh untuk keputusan menggunakan agregasi mingguan adalah merencanakan promsoi mingguan berdasarkan fluktuasi mingguan, misalkan promo untuk setiap minggu ke 4 karena lebih banyak pelanggan yang melakukan transaksi di minggu tersebut.
"""