# -*- coding: utf-8 -*-
"""HW_Regression_Alfiah_Zalfa_Tsabitah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HgVTUoCpm3Gh_N4XpfVg-HgxKcCDVXDV

# Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error

"""# Data Overview

### Load Dataset
"""

Z = pd.read_csv('/content/sample_data/boston.csv')
Z.head(10)

"""### Data Information"""

Z.info()

"""Data yang digunakan terdiri dari 506 data dengan 14 kolom, dimana type data yang digunakan adalah int64 dan float64. Jika dilihat dari informasi diatas, semua kolom memiliki 506 data yang artinya tidak ada data yang kosong. Data tersebut merupakan data yang diambil dari kaggle, data dari Boston Standard Metropolitan Statistical Area (SMSA) pada tahun 1970.

1. crim : tingkat kejahatan per kapita di setiap kota
2. zn : proporsi lahan perumahan untuk kavling dengan luas lebih dari 25.000 kaki persegi
3. indus : proporsi lahan bisnis non-ritel di setiap kota
4. chas :menandakan wilayah yang berbatasan dengan sungai Charles, 1 menandakan berbatasan, 0 tidak berbatasan
5. nox : konsentrasi nitrogen oksida (bagian per 10 juta)
6. rm : rata-rata jumlah kamar per hunian
7. age : proporsi unit hunian milik sendiri yang dibangun sebelum tahun 1940
8. dis : jarak ke 5 pusat kawasan kerja di Boston
9. rad : indeks aksesibilitas terhadap jalan raya radial
10. tax : tarif pajak properti berdasarkan nilai penuh per \$10.000
11. ptratio : rasio murid-guru di setiap kota
12. black : penduduk kulit hitam di setiap kota
13. lstat : persentase penduduk dengan status sosial ekonomi rendah
14. medv : nilai median rumah yang dimiliki oleh pemiliknya dalam \$1000

"""

# ubah semua data ke float
Z = Z.astype(float)

# cek statistik data
Z.describe().T

"""### Cek missing value"""

# cek nilai 0
Z.isnull().sum()

"""### Identifikasi variabel

yang ingin diidetifikasi adalah mengenai studi kasus prediksi harga rumah, oleh karena itu berdasarkan informasi data yang paling relevan untuk dijadikan target utama adalah kolom medv karena merupakan harga median rumah yang dimilika oleh pemilik rumah. Sedangkan faktor lain yang mendukung prediksi harga rumah dilihat melalui korelasi antara kolom mdev dengan kolom yang lainnya dan dilihat menggunakan heatmap mana yang warnanya paling gelap.
"""

corr_medv = Z.corr()['medv'].sort_values(ascending=False)

plt.figure(figsize=(6,8))
sns.heatmap(
    corr_medv.to_frame(),
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)
plt.title("Korelasi Variabel terhadap MEDV")
plt.show()

"""berdasarkan heatmap diatas 5 kolom yang memiliki korelasi paling kuat terhadap kolom mdev adalah :
1. kolom lstat yang menjelaskan mengenai kondisi ekonomi, dimana area dengan tingkat ekonomi yang rendah cenderung memiliki harga rumah lebih rendah
2. kolom rm yang menjelaskan mengenai jumlah kamar yang menjelaskan juga mengenai seberapa besar rumah tersebut, dimana semakin banyak kamar maka semakin tinggi harga rumah
3. kolom ptratio yang menjelaskan mengenai pendidikan, dimana jika rasio murid-guru tinggi artinya kualitas pendidikan rendah dan harga rumah akan semakin rendah
4. kolom indus yang menjelaskan mengenai persentase area bisnis non retail, dimana ketika banyak industri maka harga rumah akan rendah karena lingkungan yang kurang mendukung
5. kolom tax yang menjelaskan mengenai harga pajak, dimana smakin tinggi harga pajaknya maka harga rumah akan cenderung rendah dikarenakan banyak orang yang tidak tertarik dengan pajak yang tinggi
"""

# memisahkan data
selected_columns = ['medv', 'rm', 'ptratio', 'indus', 'tax', 'lstat']

A = Z[selected_columns]
A.head(5)

"""# Data Preparation

### Exploration Data Analysis
"""

# Statistik deskriptif
print("\n=== Statistik deskriptif ===")
print(A.describe().T)

# Histogram
A.hist(bins=20, figsize=(12,10))
plt.suptitle("=== Distribusi Data ===")
plt.show()

"""1. medv : Mayoritas rumah berada pada angka 15–25, namun terdapat beberapa rumah yang sangat mahal yang menunjukan adanya outlier dan didukung dengan distribusinya agak right-skewed.
2. rm : Mayoritas kamar berada pada angka 5-7 dan distribusi yang ditunjukan normal, sehingga tidak terdapat outlier.
3. ptratio : Mayoritas rasio murid-guru di sekitar 20, namun terdapat juga jumlah yang rendah sekitar 12-14 yang menunjukan adanya outlier.
4. indus : Mayoritas area berada pada angka yang rendah 0-10, namun terdapat beberapa yang tinggi >27 yang menunjukan adanya outlier dan disukung dengan distribusi yang right-skewed.
5. tax : Mayoritas pajak berada pada angka 600 an, dan terdapat outlier yang didukung dnegan distribusi yang right-skewed.
6. lstat : Mayoritas berada pada angka 4-20, namun terdapat juga jumlah yang tinggi diatas 25 yang menunjukan adanya outlier dan didukung dengan distribusi yang right-skewed.

Dikarenakan banyaknya data yang terdapat outlier, maka perlu menghilangkan outliernya. Langkah yang diambil adalah dengan menggunakan metode Log Transformation. Alasan menggunakan Log Transformation adalah dapat membuat distribusi lebih normal tanpa menghapus data.
"""

A.loc[:, 'medv']    = np.log(A['medv'])
A.loc[:, 'indus']   = np.log(A['indus'] + 1)
A.loc[:, 'tax']     = np.log(A['tax'])
A.loc[:, 'lstat']   = np.log(A['lstat'] + 1)
A.loc[:, 'ptratio'] = np.log(A['ptratio'])
A.loc[:, 'rm']      = np.log(A['rm'])

"""### Split Data"""

# split data
x = A.drop(['medv'], axis = 1)
y = A['medv']

# split data train dan val_test
x_train, x_val_test, y_train, y_val_test = train_test_split(x,y, test_size = 0.3, random_state = 42)

# split data val_test menjadi validation dan testing
x_val, x_test, y_val, y_test = train_test_split(x_val_test, y_val_test, test_size=0.5, random_state=42)

# Standardisasi data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_val_scaled = scaler.transform(x_val)
x_test_scaled = scaler.transform(x_test)

# Verifikasi pembagian data
print("Train:", len(x_train_scaled))
print("Validation:", len(x_val_scaled))
print("Test:", len(x_test_scaled))

"""### Perbandingan peran split data

1. Train : model belajar dengan data yang ada. Model menyesuaikan dengan data historis.
2. Validation : untuk mencegah model itu menghafal data train, sehingga dapat menyebabkan overfitting. Model diuji menggunakan data yang mirip namun berbeda dengan data pada train.
3. Test : evaluasi model setelah melakukan train dan validation, sehingga dapat mengetahui apakah model yang dirancang dapat diaplikasikan pada data baru.

# Analisis Korelasi dan Seleksi Fitur

### Analisis Korelasi
"""

corr_matrix = x_train.join(y_train).corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

"""### Seleksi Fitur menggunakan VIF"""

from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

df = add_constant(x_train)

vif_df = pd.DataFrame([variance_inflation_factor(df.values, i)
               for i in range(df.shape[1])],
              index=df.columns).reset_index()
vif_df.columns = ['feature','vif_score']
vif_df = vif_df.loc[vif_df.feature!='const']
vif_df

"""# Pelatihan Model"""

alphas = [0.01, 0.1, 1, 10, 100]

"""### Linear Regression"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train_scaled, y_train)

"""### Regression Ridge"""

# RMSE
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

ridge_results = []
for alpha in alphas:
    ridge = Ridge(alpha=alpha)
    ridge.fit(x_train_scaled, y_train)
    y_val_pred = ridge.predict(x_val_scaled)
    ridge_results.append({'alpha': alpha, 'RMSE': rmse(y_val, y_val_pred)})

ridge_df = pd.DataFrame(ridge_results)
best_ridge_alpha = ridge_df.loc[ridge_df['RMSE'].idxmin(), 'alpha']
ridge_best = Ridge(alpha=best_ridge_alpha)
ridge_best.fit(x_train_scaled, y_train)

"""### Regression Lasso"""

lasso_results = []
for alpha in alphas:
    lasso = Lasso(alpha=alpha)
    lasso.fit(x_train_scaled, y_train)
    y_val_pred = lasso.predict(x_val_scaled)
    lasso_results.append({'alpha': alpha, 'RMSE': rmse(y_val, y_val_pred)})

lasso_df = pd.DataFrame(lasso_results)
best_lasso_alpha = lasso_df.loc[lasso_df['RMSE'].idxmin(), 'alpha']
lasso_best = Lasso(alpha=best_lasso_alpha)
lasso_best.fit(x_train_scaled, y_train)

"""### Visualisasi Hasil Training"""

# Visualisasi RMSE vs Alpha
fig, (fig1, fig2) = plt.subplots(1, 2, figsize=(14, 5))

# Ridge
fig1.plot(ridge_df['alpha'], ridge_df['RMSE'], 'o-', linewidth=2, markersize=8, color='blue')
fig1.set_xlabel('Alpha', fontsize=12)
fig1.set_ylabel('RMSE (Validation)', fontsize=12)
fig1.set_title('Ridge: RMSE vs Alpha', fontsize=14)
fig1.grid(True, alpha=0.3)
fig1.set_xscale('log')

# Lasso
fig2.plot(lasso_df['alpha'], lasso_df['RMSE'], 'o-', linewidth=2, markersize=8, color='green')
fig2.set_xlabel('Alpha', fontsize=12)
fig2.set_ylabel('RMSE (Validation)', fontsize=12)
fig2.set_title('Lasso: RMSE vs Alpha', fontsize=14)
fig2.grid(True, alpha=0.3)
fig2.set_xscale('log')

plt.tight_layout()
plt.show()

print(f"Ridge Best Alpha: {best_ridge_alpha} dengan RMSE: {ridge_df.loc[ridge_df['alpha']==best_ridge_alpha, 'RMSE'].values[0]:.4f}")
print(f"Lasso Best Alpha: {best_lasso_alpha} dengan RMSE: {lasso_df.loc[lasso_df['alpha']==best_lasso_alpha, 'RMSE'].values[0]:.4f}")

"""Analisis Hasil Training : Grafik tersebut menunjukan bahwa alpha terbaik untuk ridge berada pada nilai 100 dan alpha terbaik untuk lasso berada pada nilai 0.01.

### Perbandingan Ridge vs Lasso

1. Ridge Regression : Menghasilkan kurva RMSE yang lebih smooth saat alpha berubah. Lebih cocok ketika semua variabel dianggap penting dalam memprediksi.

2. Lasso Regression : Menghasilkan kurva RMSE yang berubah tajam saat alpha berubah. Lebih cocok digunakan jika ingin menggunakan sedikit variabel.

# Interpretasi Model

### Analisis Koefisien Model
"""

# Analisis koefisien model
feature = x_train.columns.tolist()

coef_comp = pd.DataFrame({
    'Feature': feature,
    'Linear Regression': lr.coef_,
    'Ridge': ridge_best.coef_,
    'Lasso': lasso_best.coef_
})

print("\n=== Perbandingan Koefisien Model ===")
print(coef_comp)

"""### Fitur Paling Relevan untuk Prediksi Harga Rumah

Berdasarkan HeatMap:
- Pengaruh positif terbesar: **rm** (jumlah kamar), dimana semakin banyak kamar, harga rumah semakin tinggi
- Pengaruh negatif terbesar: **lstat** (status ekonomi rendah), dimana semakin tinggi proporsi penduduk berstatus ekonomi rendah, harga rumah semakin rendah

# Evaluasi Model
"""

def mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred)/y_true)) * 100

# Prediksi menggunakan scaled data
model_results = {}
models = {
    "Linear Regression": (lr, x_train_scaled, x_test_scaled),
    f"Ridge (alpha={best_ridge_alpha})": (ridge_best, x_train_scaled, x_test_scaled),
    f"Lasso (alpha={best_lasso_alpha})": (lasso_best, x_train_scaled, x_test_scaled)
}

print("HASIL EVALUASI MODEL PREDIKSI HARGA RUMAH")

for name, (model, x_tr, x_te) in models.items():
    y_train_pred = model.predict(x_tr)
    y_test_pred = model.predict(x_te)

    train_rmse = rmse(y_train, y_train_pred)
    test_rmse = rmse(y_test, y_test_pred)
    train_mae = mean_absolute_error(y_train, y_train_pred)
    test_mae = mean_absolute_error(y_test, y_test_pred)
    train_mape = mape(y_train, y_train_pred)
    test_mape = mape(y_test, y_test_pred)

    model_results[name] = {
        'Train RMSE': train_rmse,
        'Test RMSE': test_rmse,
        'Train MAE': train_mae,
        'Test MAE': test_mae,
        'Train MAPE': train_mape,
        'Test MAPE': test_mape
    }

    print(f"\n=== {name} ===")
    print(f"Train RMSE: {train_rmse:.4f}  |  Test RMSE: {test_rmse:.4f}")
    print(f"Train MAE:  {train_mae:.4f}  |  Test MAE:  {test_mae:.4f}")
    print(f"Train MAPE: {train_mape:.2f}%   |  Test MAPE: {test_mape:.2f}%")

    # Cek overfitting
    rmse_diff = test_rmse - train_rmse
    if rmse_diff > 0.05:
        print(f"Indikasi OVERFITTING  {rmse_diff:.4f}")
    elif rmse_diff < -0.05:
        print(f"Indikasi UNDERFITTING {rmse_diff:.4f}")
    else:
        print(f"Model stabil")

"""**Metrik Evaluasi:**
1. RMSE (Root Mean Squared Error) : Menghitung akar rata-rata kesalahan kuadrat
2. MAE (Mean Absolute Error) : Menghitung rata-rata kesalahan absolut
3. MAPE (Mean Absolute Percentage Error) : Menghitung persentase kesalahan relatif

# Reflection Question

1. Mengapa penting memahami konsep regularisasi seperti Ridge dan Lasso dalam membangun model regresi? Bagaimana teknik ini membantu meningkatkan performa model dalam kasus prediksi dunia nyata seperti harga rumah?

   Karena konsep Ridge dan Lasso sangat penting dalam membangun model regresi karena teknik ini membantu mengatasi masalah multicollinearity dan overfitting, yang sering muncul ketika beberapa fitur memiliki korelasi tinggi atau data terlalu spesifik pada data historis. Ridge memperkecil semua koefisien  sehingga model menjadi lebih stabil, sementara Lasso menghapus fitur yang kurang relevan, sehingga model lebih sederhana dan interpretatif.

2. Bagaimana proses analisis korelasi, seleksi fitur, dan pemilihan model berdasarkan validation set membantu kamu membangun model yang lebih akurat dan dapat dipercaya? Apa hal yang paling kamu pelajari dari tahapan tersebut?

   Proses analisis korelasi, seleksi fitur, dan pemilihan model berdasarkan validation set membantu membangun model yang lebih baik, akurat dan dapat dipercaya. Analisis yang dilakukan dapat memberikan gambaran antar fitur dan validation digunakan untuk mrmilih hyperparameter yang bagus agar model tidak overfit. Hal yang paling dipelajari adalah ketika menentukan fitur yang relevan dan menguji menggunakan data testing yang sebelumnya belum pernah dipelahari pada data training.
"""